# Frontend Dockerfile
FROM node:22 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest
# Copiar los archivos construidos del frontend
COPY --from=builder /app/dist /usr/share/nginx/html
# Copiar la configuración de nginx
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]