global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb_exporter:9104']
