global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nginx_exporter'
    dns_sd_configs:
      - names:
        - 'api.monitoring.local'
        type: 'A'
        port: 9113

  - job_name: 'api'
    dns_sd_configs:
      - names:
        - 'api.monitoring.local'
        type: 'A'
        port: 5000

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'mariadb'
    dns_sd_configs:
      - names:
        - 'mariadb.monitoring.local'
        type: 'A'
        port: 9104